# Generated by Django 4.2 on 2023-04-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
