# Generated by Django 4.2 on 2023-04-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcart', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DoB',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
